### ISSUE TITLE
Xbox App

### ISSUE THREAD

**Issue by air720boarder** [iVoider/PlayCover#101]
I'm trying to run the Xbox app so I can stream locally from my Xbox and play (or stream from x-cloud). It doesn't appear to be working. Please add support!

**Comment by iVoider** [comment]
It works. Use PlaySign

**Comment by Ares6x** [comment]
Hi it definitely does not work. I've tried it with SIP on and off and PlaySign on and off (using the decryptedipas app and my pull of the iPad). It crashes immediately and gives and a crash report.

![Screen Shot 2022-03-04 at 10 28 22 AM](https://user-images.githubusercontent.com/100956286/156801457-95a50fd3-7855-4f56-8517-453e91fd09e2.png)

**Comment by Alonxx** [comment]
Same problem, no have fix?
