### ISSUE TITLE
PlayCover not working

### ISSUE THREAD

**Issue by Bkm016** [iVoider/PlayCover#102]
我通过完全正常的途径安装 PlayCover：
1. 从 https://www.playcover.me 下载 0.9.7 版本 .dmg 文件
2. 双击安装
3. 启动后提示：You don’t have permission to save the file “Frameworks” in the folder “Library”.

---

I installed PlayCover the completely normal way:
1. Download the version 0.9.7 .dmg file from https://www.playcover.me
2. Double click to install
3. Prompt after startup: You don’t have permission to save the file “Frameworks” in the folder “Library”.

--- 

相同的问题：
https://github.com/iVoider/PlayCover/issues/81

**Comment by Bkm016** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/27818531/151917604-0031c570-7c92-4c6a-86eb-ff63d8bf4df5.png">

**Comment by iVoider** [comment]
You need admin account for this. And place PlayCover inside Applications folder.
