### ISSUE TITLE
Genshin Impact Crashes During Character Movement

### ISSUE THREAD

**Issue by sedatedcorpse** [iVoider/PlayCover#103]
This was an unwanted surprise, I was playing Genshin Impact on my M1 Macbook Air last night. Everything ran fine no hiccups, no stuttering just a few frame drops due to overheating (Because the M1 Air has no fan) I wake up today and the game launches without a hitch, goes to the loading screen then looks to be going well. All of a sudden It just crashes for no reason. At first I thought it was my controller, I tried disconnecting it and relaunched the game yet the same problem occured. I soon found out that it wasn't my controller but it was interacting with the character that was causing the issue. I find strange as scrolling through the menu page and checking the shop or friends list doesn't cause this issue. It is only caused when you are actually playing. If anyone has any ideas please help. The only thing I can think of is my Mac is trying to tell me something as I spend days in a row on the game :)

**Comment by iVoider** [comment]
You can try reseting keymapping in App Settings. Otherwise, I fear only system reinstall will help you

**Comment by kxlv2000** [comment]
It may be the problem of the midi audio output sampling rate, if I set it to 88.2k or 96kHz, the game 100% will freeze then crash when the characters move, change it to 44.1k or 48kHz will be perfectly solved to me.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/49295281/162599251-45765fa9-2d6e-4c16-bb55-2e1924f306c7.png">

**Comment by zwj326** [comment]
> 
It sovles my problem. Thank you so much.

**Comment by NikarashiHatsu** [comment]
> It may be the problem of the midi audio output sampling rate, if I set it to 88.2k or 96kHz, the game 100% will freeze then crash when the characters move, change it to 44.1k or 48kHz will be perfectly solved to me. <img alt="image" width="765" src="https://user-images.githubusercontent.com/49295281/162599251-45765fa9-2d6e-4c16-bb55-2e1924f306c7.png">

How is this fix the issue? Is there any explanation on why this crashes Genshin?

**Comment by zwj326** [comment]
The solution replied by kxlv2000 should be the key factor of the crash.> You can try reseting keymapping in App Settings. Otherwise, I fear only system reinstall will help you

**Comment by sedatedcorpse** [comment]
After your @kxlv2000 concise explanation of the sound output. I found somehow, I had changed the setting to 88.4k. In saying that. I have since changed the audio too 44.1k which resolved the issue. My gratitude goes to you, I appreciate the feedback given as I will now enjoy playing genshin <3
