### ISSUE TITLE
please dont prevent to play pubg and sgame

### ISSUE THREAD

**Issue by tuancc-hub** [iVoider/PlayCover#108]
thanks
we dont care about ban...
please set the ban message just a message
and then let it run to play
dont prevent to run it

**Comment by iVoider** [comment]
Many people don’t read text, and then whining on Discord. Any case unless the better jailbreak hide system will be released, you will receive immediate ban on launch.

**Comment by tuancc-hub** [comment]
Apple mac users are high-income and influential groups. When the game company bans their account, they will make a noise and force the game company to authenticate the matter, instead of us directly banning playing games through playcover, This way things will never be resolved, of course, playcover can pop up a prompt.

**Comment by tuancc-hub** [comment]
please allow to play,  with a tips.

**Comment by L1cardo** [comment]
Yeah, I am response for what I am doing!!!
