### ISSUE TITLE
Download link for Genshin/Yuanshen doesn't work

### ISSUE THREAD

**Issue by edward-martyr** [iVoider/PlayCover#110]
My browser takes me to <https://drive.google.com/file/d/1Wdy2c40Zpt32zOH7avuER3epzuo9ecLC/view?usp=sharing>, which is a nonexistent file.

**Comment by Animenosekai** [comment]
Join the discord server, new links are being added daily

https://discord.gg/playcover

**Comment by edward-martyr** [comment]
@Animenosekai I remember in the tutorial videos that there is an `.IPA` file channel, but I can't find it (I haven't used Discord for a long time…)

<img width="1197" alt="スクリーンショット 2022-02-16 10 58 08" src="https://user-images.githubusercontent.com/42882301/154304790-fc67bbbc-b8b2-4c09-924d-ff630d33ab0b.png">

**Comment by edward-martyr** [comment]
I managed to find a link under <https://ipa.playcover.workers.dev/0:/> to Genshin: <https://ipa.playcover.workers.dev/0:/CN/%E5%8E%9F%E7%A5%9E_2.5.ipa>, but it wouldn't work, and gives an error:

```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidAbuseAcknowledgment",
    "message": "This file has not been flagged for abuse.",
    "locationType": "parameter",
    "location": "acknowledgeAbuse"
   }
  ],
  "code": 403,
  "message": "This file has not been flagged for abuse."
 }
}
```

**Comment by wsyconan** [comment]
@edward-martyr Discord 频道里确实有下载链接：https://mega.nz/file/wwsykSyS#ZsO8rTI8Ot2au-fFF2iaQZP1jWmOBj9Wj5r0NsLwPN4

**Comment by Animenosekai** [comment]
> @Animenosekai I remember in the tutorial videos that there is an `.IPA` file channel, but I can't find it (I haven't used Discord for a long time…)
> 
> 
> 
> <img width="1197" alt="スクリーンショット 2022-02-16 10 58 08" src="https://user-images.githubusercontent.com/42882301/154304790-fc67bbbc-b8b2-4c09-924d-ff630d33ab0b.png">
> 
> 

Read the rules there should be somewhere to get verified, click on the thing to get verified and you will have access to the channel to download the `.ipa`

**Comment by edward-martyr** [comment]
@Animenosekai This helped; thanks a lot!

**Comment by edward-martyr** [comment]
> @edward-martyr Discord 频道里确实有下载链接：https://mega.nz/file/wwsykSyS#ZsO8rTI8Ot2au-fFF2iaQZP1jWmOBj9Wj5r0NsLwPN4

Thanks
