### ISSUE TITLE
Genshin Impact can't download.

### ISSUE THREAD

**Issue by jason0973070580** [iVoider/PlayCover#111]
https://ipa.playcover.workers.dev/0:/US/Genshin%20Impact_2.5.ipa Can't download Genshin Impact.
https://mega.nz/file/wwsykSyS#ZsO8rTI8Ot2au-fFF2iaQZP1jWmOBj9Wj5r0NsLwPN4 Can be used but the download is Yuanshen not Genshin.
I can only log in to Genshin but not Yuanshen.

**Comment by YuriSequoia** [comment]
Please join the [discord channel](https://discord.gg/playcover) and download it using the latest web link in the ["decrypted-ipas"](https://discord.com/channels/871829896492642387/918279999209996288).
And
```
Don't create issue here if you are not dev
```
