### ISSUE TITLE
DualShock4 wireless controller not work for yuanshen2.5

### ISSUE THREAD

**Issue by fubukishiro** [iVoider/PlayCover#122]
I tried to run the yuanshen 2.5 on Mac M1 with MacOS12.3 and to control via DualShock4. However I can not switch to the DualShock4 in the yuanshen's setup.

**Comment by AGou-ops** [comment]
I have same issue with my Xbox controller. But I solved the problem by restarting the computer.

**Comment by AGou-ops** [comment]
https://developer.apple.com/forums/thread/702254
https://www.reddit.com/r/apple/comments/texs5a/controller_support_completely_broken_with_macos/

**Comment by fubukishiro** [comment]
> I have same issue with my Xbox controller. But I solved the problem by restarting the computer.
> 
> **If once doesn't work, then twice...**

It works by restarting! Thanks a lot!
