### ISSUE TITLE
PlayCover 1.0.0 Genshin 120FPS

### ISSUE THREAD

**Issue by Bingodingguagua** [iVoider/PlayCover#129]
PlayCover 1.0.0 : "120 FPS support in more games including Genshin. How to enable: switch between 30 and 60 FPS in Settings and back" 
But I have not found 120fps option in the game setting

**Comment by Bingodingguagua** [comment]
But the actual performance is 120fps, need to switch 120fps option in PlayCover's genshin app setting.

**Comment by zanderp25** [comment]
The 120 fps option itself does not show up, it still says 60 FPS but runs at 120
