### ISSUE TITLE
到底有没有intel版本了，开发者是不是放弃开发intel了

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [iVoider/PlayCover#134]

**Comment by NullYing** [comment]
Run iOS apps & games on M1 Mac with mouse, keyboard and controller support.

**Comment by wsw-black** [comment]
期待能尽快出intel版本

**Comment by nyaasuki** [comment]
不会有intel版本

**Comment by shoudeyunkaijianyueming** [comment]
> 不会有intel版本

你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答

**Comment by wlunc** [comment]
> > 不会有intel版本
> 
> 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答

这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的

**Comment by shoudeyunkaijianyueming** [comment]
> > > 不会有intel版本
> > 
> > 
> > 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
> 
> 这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发

**Comment by nyaasuki** [comment]
> > > > 不会有intel版本
> > > 
> > > 
> > > 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
> > 
> > 
> > 这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
> > 好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发

希望你知道所谓的intelmac的原生只限于开发 需要额外的包 在应用市场里的应用是不可原生运行在intelmac上的，除非你是用IDE进行模拟，这个软件的原理是直接侧载ios应用而不是模拟IDE环境 这没有任何意义 效能很低

**Comment by nyaasuki** [comment]
事实上我的理解这个软件的意义是键位模拟 而不是解决如何在intel上原生运行ios应用

**Comment by NullYing** [comment]
> 事实上我的理解这个软件的意义是键位模拟 而不是解决如何在intel上原生运行ios应用

笑哭，这软件并不是按键模拟

**Comment by nyaasuki** [comment]
> > 事实上我的理解这个软件的意义是键位模拟 而不是解决如何在intel上原生运行ios应用
> 
> 笑哭，这软件并不是按键模拟，intel应该不太可能了

坦诚的说 按键映射这个功能按照说明使用我也没有成功 🥲

**Comment by NullYing** [comment]
> > > 事实上我的理解这个软件的意义是键位模拟 而不是解决如何在intel上原生运行ios应用
> > 
> > 
> > 笑哭，这软件并不是按键模拟，intel应该不太可能了
> 
> 坦诚的说 按键映射这个功能按照说明使用我也没有成功 🥲

买手柄比较好用，没有手柄真的很难玩

**Comment by NullYing** [comment]
> > > > > 不会有intel版本
> > > > 
> > > > 
> > > > 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
> > > 
> > > 
> > > 这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
> > > 好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发
> 
> 希望你知道所谓的intelmac的原生只限于开发 需要额外的包 在应用市场里的应用是不可原生运行在intelmac上的，除非你是用IDE进行模拟，这个软件的原理是直接侧载ios应用而不是模拟IDE环境 这没有任何意义 效能很低

win的x86原神走crossover可能还能有希望，ios的包并没有x86，所以intel的跑不了arm程序，至少是ios的原神不行

**Comment by shoudeyunkaijianyueming** [comment]
> > > > > > 不会有intel版本
> > > > > 
> > > > > 
> > > > > 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
> > > > 
> > > > 
> > > > 这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
> > > > 好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发
> > 
> > 
> > 希望你知道所谓的intelmac的原生只限于开发 需要额外的包 在应用市场里的应用是不可原生运行在intelmac上的，除非你是用IDE进行模拟，这个软件的原理是直接侧载ios应用而不是模拟IDE环境 这没有任何意义 效能很低
> 
> win的x86原神走crossover可能还能有希望，ios的包并没有x86，所以intel的跑不了arm程序，至少是ios的原神不行

看你们两个好像比开发者还懂，看你们不是开发者我放心了😹

**Comment by e-su** [comment]
> > > > > > > 不会有intel版本
> > > > > > 
> > > > > > 
> > > > > > 你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
> > > > > 
> > > > > 
> > > > > 这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
> > > > > 好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发
> > > 
> > > 
> > > 希望你知道所谓的intelmac的原生只限于开发 需要额外的包 在应用市场里的应用是不可原生运行在intelmac上的，除非你是用IDE进行模拟，这个软件的原理是直接侧载ios应用而不是模拟IDE环境 这没有任何意义 效能很低
> > 
> > 
> > win的x86原神走crossover可能还能有希望，ios的包并没有x86，所以intel的跑不了arm程序，至少是ios的原神不行
> 
> 看你们两个好像比开发者还懂，看你们不是开发者我放心了😹

iOS目前没有模拟器，只能原生运行，intel不支持原生运行。要是作者能支持intel版本的Mac，那他就是开发出iOS模拟器的第一人。我也挺期待。

**Comment by wsw-black** [comment]
非常感谢您对于此问题的解答，只是希望这个东西可以在intel版本的电脑上实现而已，对于这些方面并没有深入的了解，希望能有更多的机会向您学习。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iVoider/PlayCover"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iVoider/PlayCover] 到底有没有intel版本了，开发者是不是放弃开发intel了 (Issue #134)





        
不会有intel版本
  
你是开发者么，如果是我听到这个消息感觉很失望，但是仍然希望这个软件越来越好；如果不是开发者，请你不要随意回答
  
这个的原理就是因为M1的芯片和iOS一样是ARM架构，所以包是通用的，Intel的mac，cpu架构是x86，没办法安装iOS的包的
 好好看看以前开发者的回复吧，ios安装器在intel mac本来就是原生的，现在的问题不是原理通不通，而且开发者是否开发
   
希望你知道所谓的intelmac的原生只限于开发 需要额外的包 在应用市场里的应用是不可原生运行在intelmac上的，除非你是用IDE进行模拟，这个软件的原理是直接侧载ios应用而不是模拟IDE环境 这没有任何意义 效能很低
  
win的x86原神走crossover可能还能有希望，ios的包并没有x86，所以intel的跑不了arm程序，至少是ios的原神不行
  
看你们两个好像比开发者还懂，看你们不是开发者我放心了😹
  
iOS目前没有模拟器，只能原生运行，intel不支持原生运行。要是作者能支持intel版本的Mac，那他就是开发出iOS模拟器的第一人。我也挺期待。
