### ISSUE TITLE
App Architecture

### ISSUE THREAD

**Issue by gabrielv33** [iVoider/PlayCover#14]
The ReadMe is severely lacking and there is no documentation. How does the app actually function? Is there some virtualisation involved? Any there any preliminary performance metrics?

**Comment by dltacube** [comment]
Would there be virtualization if it only runs apps on M1? It's native.

**Comment by gabrielv33** [comment]
Of course there would normally be. These are two different operating systems. The microprocessor architecture is the same, yes, but the software is not - which usually implies virtualisation is used.

**Comment by Letscoder** [comment]
> Of course there would normally be. These are two different operating systems. The microprocessor architecture is the same, yes, but the software is not - which usually implies virtualisation is used.

What? iOS apps on Mac M1 are supported natively. Apple programmers just writed Catalyst libraries for all corresponding iOS libraries. PlayCover uses same tech, but with another UNIX execution type. So it is native.
I will write a more detailed read me when I have time.

**Comment by iVoider** [comment]
Since 0.8.9 PlayCover uses plain native iOS apps, so no more magic.
