### ISSUE TITLE
Sending SIGSTOP to app causes audio glitch

### ISSUE THREAD

**Issue by jonathan2384** [iVoider/PlayCover#170]
# Issue Description
Sending a SIGSTOP (with Activity Monitor or Terminal `kill -stop pid`) results in the game's (Genshin Impact) audio glitching. The glitching persists until either the app is resumed with SIGCONT `kill -CONT pid` or the coreaudiod process is killed.

**Comment by iVoider** [comment]
Use 44/48 hz sound device in Settings
