### ISSUE TITLE
Unable to bind 'K' key

### ISSUE THREAD

**Issue by Azarattum** [iVoider/PlayCover#181]
After version 0.9.9 binding 'K' key no longer works. Pressing the key does not cause a touch button to trigger. It just does nothing. My guess is that is related to `Now you can Command + K to open editor with cursor hidden` feature. Tested in Genshin Impact.

Current solution: use 0.9.8 or lower.

**Comment by iVoider** [comment]
Fixed with 1.0.2 version on Patreon
