### ISSUE TITLE
.dmg version 1.0.1 file is broken and doesn't run

### ISSUE THREAD

**Issue by HaidarChaito** [iVoider/PlayCover#188]

**Comment by iVoider** [comment]
Updated DMG

**Comment by Marsman1996** [comment]
The .dmg file is still broken, downloaded in the [release page](https://github.com/iVoider/PlayCover/releases/download/1.0.1/PlayCover1.0.1.dmg).

The shasum is a9646d9e5a7c495ff9e202c8c9065e8db94ac3b6.
