### ISSUE TITLE
version 1.0.1 break Honkai Impact 3rd

### ISSUE THREAD

**Issue by HaidarChaito** [iVoider/PlayCover#193]
after the 1.0.1 update Honkai impact ingame camera stop following the character completely which totally break the game.
p.s: the bug is only on version 1.0.1
what i tried:
-re-download the launcher 
-re-install the game from scratch
-fully reset the mac (starting from 0)
after downgrading to version 1.0.0 the bug is fixed ( even without re downloading the game )

**Comment by iVoider** [comment]
Issue was fixed in Patreon 1.0.2 version
