### ISSUE TITLE
Many iOS apps such as Fruitz now crash when using PlayCover version 1.0.4 with PlaySign

### ISSUE THREAD

**Issue by devnoname120** [iVoider/PlayCover#200]
For example Fruitz used to work but it doesn't anymore with PlaySign. It crashes right on start.
https://ipa.playcover.workers.dev/0:/US/Fruitz_2.10.5.ipa

If I disable PlaySign then I can't log in. In the previous version 1.0.1 Fruitz used to work great and login as well as long as PlaySign was enabled (otherwise login wouldn't work).

**Comment by AgeeZhang** [comment]
same for wechat

**Comment by luongdnt** [comment]
same to AFK Arena
