### ISSUE TITLE
[0.8.7] Cannot control camera with mouse in Genshin Impact

### ISSUE THREAD

**Issue by swb1234554321** [iVoider/PlayCover#48]
Hi,

With the latest 0.8.7 version, it is impossible control the camera and move at the same time. Does it have anything to do with the feature "invalidate all touches on Alt press"?

Thanks!

**Comment by swb1234554321** [comment]
MacOS Monterey12.0, with m1 max chip.

**Comment by sooxt98** [comment]
Doest work on M1 BigSur 11.6 too

**Comment by lun0309** [comment]
Same here with my m1 macbook pro running MacOS Monterey12.0.

The camera cannot move with mouse

**Comment by zcc0030** [comment]
MacBook Pro 16‘ 2021  M1max cannot control camera with mouse

**Comment by xEzeit** [comment]
> MacBook Pro 16‘ 2021 M1max cannot control camera with mouse

Same issue

**Comment by ZiYang1989** [comment]
同样的问题。。。鼠标无法转向，只能响应几个按键

**Comment by zcc0030** [comment]
> 同样的问题。。。鼠标无法转向，只能响应几个按键

我去买了个ps4手柄，在游戏设置里调整为手柄模式，就完美了

**Comment by czy-moyu** [comment]
same to me, can not control camera with my mouse.

**Comment by lun0309** [comment]
> > 同样的问题。。。鼠标无法转向，只能响应几个按键
> 
> 
> 
> 我去买了个ps4手柄，在游戏设置里调整为手柄模式，就完美了

Thanks for suggestion

**Comment by lun0309** [comment]
The 0.8.9 has solved this problem, the mouse can control the camera now, thanks a lot

**Comment by Shunjun** [comment]
I upgrade to 0.8.9 and 0.9.1, the camera also cannot be controlled with my mouse.
Monterey 12.0.1 with m1.

**Comment by mingjun97** [comment]
Same issue. 

I'm new to this app. I have hard time seting up key mappings (in 0.9.1) using mouse as the cursor tends to hide all the time. I roll back to version 0.8.9 to setup the key mapping and upgrade to 0.9.1 again.

But the camera position still could not be moved. And the mouse cursor still invisible.
Monterey 12.0.1 with m1.

**Comment by twiceyuan** [comment]
v0.9.2 has some issue. 
Env info: 
- Model Identifier:	MacBookPro18,3
- macOS Monterey 12.0.1 (21A559)

**Comment by swb1234554321** [comment]
Has been fixed with the TOT version, close the issue.
