### ISSUE TITLE
Any chance to test 0.9.3? I cannot disable SIP

### ISSUE THREAD

**Issue by CharlieBrown12** [iVoider/PlayCover#58]
As the title says - I would love to test 0.9.3, as I cannot test with SIP disabled.

**Comment by AnnesteDev** [comment]
**Do you want get the latest features or maybe you want my help to play as fast as possible?** 
https://www.patreon.com/playcoverapp

Supporters privileges based on sum of donation.
Every tier has every feature of below tiers.

5$ - @Dolphin : 
* Access to early builds (every 2-3 days) **<-- !!**
* Access to #supporters private chat 
* Enlist your nick inside app, website
* Ability to DM me for help

It is well worth it.

**Comment by iVoider** [comment]
Don't create issues for such things. Just wait for public release
