### ISSUE TITLE
Can not open genshin impact 2.3 in PlayCover 0.9.2

### ISSUE THREAD

**Issue by czy-moyu** [iVoider/PlayCover#59]
my machine: 13 mbp m1.

this is part of logs:
版本12.0.1（版号21A559）
/private/var/folders/4c/2g4dqgnx3c71gp4bx4f3pl480000gn/T/AppTranslocation/059E9C83-1794-4B39-84ED-121E190376E6/d/PlayCover.app/Contents/Resources/PlayTools: replacing existing signature
/private/var/folders/4c/2g4dqgnx3c71gp4bx4f3pl480000gn/T/AppTranslocation/059E9C83-1794-4B39-84ED-121E190376E6/d/PlayCover.app/Contents/Resources/PlayTools: internal error in Code Signing subsystem

System Integrity Protection status: disabled.

System Integrity Protection status: disabled.

**Comment by chmoe** [comment]
Try uninstalling it and reinstalling 0.8.9 ver, I solved it by this.

**Comment by czy-moyu** [comment]
I solved by installing decrypted ipa.
