### ISSUE TITLE
csrutil: This tool needs to be executed from Recovery OS.

### ISSUE THREAD

**Issue by wenchaser** [iVoider/PlayCover#61]
After restarting Mac and typing csrutil disable in Terminal. It returns csrutil: This tool needs to be executed from Recovery OS.
I still cannot open ipa.And it always show the instruction.

**Comment by wenchaser** [comment]
https://support.apple.com/zh-cn/guide/security/sec7d92dc49f/web

**Comment by wenchaser** [comment]
https://support.apple.com/zh-cn/guide/security/sec10869885b/web

**Comment by ryuujo1573** [comment]
You should NOT type that command from normal OS, AND as what it is said, it needs to be executed from Recovery OS, which requires you to press power button for a while BEFORE booting into your OS to boot into Recovery OS.

Read instructions carefully or give up

**Comment by iVoider** [comment]
Please, don't create issues for such things. Follow instruction: https://www.youtube.com/watch?v=mh70tXwPkY4
