### ISSUE TITLE
amfi_allow_any_signature instead of  amfi_get_out_of_my_way

### ISSUE THREAD

**Issue by sudo-gera** [iVoider/PlayCover#62]
Playcover requires nvram  boot-args `amfi_get_out_of_my_way=1` but  this breaks any DriverKit system extensions, for example, Keyboard-Karabiner app. But if I remove this arg and add `amfi_allow_any_signature=1` instead of this, IOS apps, for example, genshin impact, will still run, but other software which conflicts with `amfi_allow_any_signature=1`,as for me, thats is Keyboard-Karabiner, now works good. What about full testing if playcover can use `amfi_allow_any_signature=1` instead of `amfi_get_out_of_my_way=1` and if it can, replace this command in user instructions?

**Comment by sudo-gera** [comment]
As for now, authorization fails in genshin when allow_any_signature=1.But other ios apps work. Genshin works only when get_out_of_my_way=1

**Comment by devnoname120** [comment]
@iVoider I can confirm that most iOS apps crash for me if I use `amfi_allow_any_signature=1` instead of `amfi_get_out_of_my_way=1`.

Would it be possible to make PlayCovert compatible with `amfi_allow_any_signature=1`?
