### ISSUE TITLE
have_you_abandoned_the_intel_version？

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [iVoider/PlayCover#68]
Hope not to give up

**Comment by shoudeyunkaijianyueming** [comment]
If you don't give up, how long will it take? I'm looking forward to it

**Comment by BearTS** [comment]
@shoudeyunkaijianyueming Don't create duplicate issue
https://github.com/iVoider/PlayCover/issues/52
Refer to that
Close this issue
