### ISSUE TITLE
Schrödingers Genshin Impact / Data error or Captcha Login SIP ON or OFF

### ISSUE THREAD

**Issue by Patt92** [iVoider/PlayCover#72]
I've updated today to 0.9.5 and installed Genshin Impact 2.3 (IPA from Playcover). I started Genshin Impact and pressed on the door, error "Data error, please login again", but hey there is the smart hint "csrutil enable". O.K. went for it, restarted and opened Playcover. The game was gone...?
I reinstalled the game and opened it, tried to login no Captcha appear?
"If you have problems with captcha login, press Enable Playsign"...did so now the game shows "Data error, please login again".

So with csrutil enable
I can't login, no Captcha (in the game folder are encrypted login data, but ignored. I guess the SIP handling like decrypting IPAs)

with csrutil disable
I can't start the game, but login.

Am I logged in now, or is the captcha working...

Anyone knows how to fix this? I tried also an app cache wipe, while having SIP enabled, because installed from there the IPA shows for both states, but it was no help.

**Comment by sooxt98** [comment]
@Patt92 could you please attached a logs copy from your playcover

**Comment by Patt92** [comment]
actually I was just about to create the logs, then I've seen Release 0.9.63.
This one worked out. SIP enabled, no Captcha, SIP disabled already logged in and also playable again.
=> solved

Change 0.9.6: Fixed "Data error, please login again error" in Genshin
