### ISSUE TITLE
COD The input box cannot be entered, and I cannot log in.

### ISSUE THREAD

**Issue by lxyer** [iVoider/PlayCover#75]
The input box cannot be entered, and I cannot log in.I have disabled csrutil.
![image](https://user-images.githubusercontent.com/17336748/147304830-6f834683-a574-4946-b88a-0564ecede464.png)

**Comment by stanislavlysenko0912** [comment]
I have same problem, your fixed that?

**Comment by Animenosekai** [comment]
<img width="622" alt="Capture d’écran 0004-01-14 à 17 39 40" src="https://user-images.githubusercontent.com/40539549/149551961-7872bfb2-6f21-4a8c-a522-97dc834fb352.png">

**Comment by iVoider** [comment]
Use last 0.9.8 release
