### ISSUE TITLE
How to decide this error: You don’t have permission to save the file “Frameworks” in the folder “Library”.

### ISSUE THREAD

**Issue by NikStor03** [iVoider/PlayCover#81]
So, when i try to open Play cover, it gives me this error:

![image](https://user-images.githubusercontent.com/67559040/147856841-e248fca3-1523-4637-bff2-6890fa01f0dc.png)

I tried whith 2 variants:
1. SIP is enable
2. Sip is disable
No one works.

Please, help me 😢

**Comment by Animenosekai** [comment]
Where did you install PlayCover and do you have limited permissions to the files on the computer?

**Comment by HKSAR-Gov** [comment]
Same issue here. It is installed in Applications and I give playcover full disk access but still have the same error.

**Comment by Bkm016** [comment]
> Same issue here. It is installed in Applications and I give playcover full disk access but still have the same error.
> 
> I seem to get it running by this command in terminal: sudo /Applications/PlayCover.app/Contents/MacOS/PlayCover It would keep telling me "The file “playcover.plist” doesn’t exist." but Netflix and Genshin can run.

Running with sudo will not save keymap

**Comment by NikStor03** [comment]
> Same issue here. It is installed in Applications and I give playcover full disk access but still have the same error.
> 
> I seem to get it running by this command in terminal: sudo /Applications/PlayCover.app/Contents/MacOS/PlayCover It would keep telling me "The file “playcover.plist” doesn’t exist." but Netflix and Genshin can run.

I recently fixed this error. How? Look. Once I changed the user's nickname on the poppy itself, and I forgot to rename the folder, in order to fix this, the highlighted items must be the same.
<img width="588" alt="Screenshot 2022-02-01 at 09 16 34" src="https://user-images.githubusercontent.com/67559040/151927548-6cfc1792-ce45-4320-ab4f-0233d342980c.png">
