### ISSUE TITLE
Yuanshen can't play.

### ISSUE THREAD

**Issue by LoveJessyChen** [iVoider/PlayCover#83]
Yuanshen can't play.
It shows to upgrade to 2.3 from 2.2

**Comment by tom463113** [comment]
you can use iMazing to get IPA sources from iPad or iPhone.

**Comment by Animenosekai** [comment]
@LoveJessyChen To play Genshin Impact (Yuanshen) you need to have the latest version available. Download one from the Discord Server (Chinese Versions are also available) or decrypt one by yourself

**Comment by LoveJessyChen** [comment]
> @LoveJessyChen To play Genshin Impact (Yuanshen) you need to have the latest version available. Download one from the Discord Server (Chinese Versions are also available) or decrypt one by yourself

But link of discord is not available.

**Comment by Animenosekai** [comment]
> But link of discord is not available.

https://discord.gg/playcover

**Comment by LoveJessyChen** [comment]
> 
> 
> > But link of discord is not available.
> 
> 
> 
> https://discord.gg/playcover

Ok Thanks
