### ISSUE TITLE
Clash Royale

### ISSUE THREAD

**Issue by trodrigueza** [iVoider/PlayCover#84]
Hi, is Clash Royale playable? I tried with the iMazing IPA and it doesn't work... btw, sorry to comment the issue here but the Discord link is broken.

**Comment by Animenosekai** [comment]
You won't be able to use iMazing's IPA as it is with PlayCover as they need to be decrypted before use.

You can decrypt them with a Jailbroken iOS device or download decrypted IPAs from the Discord
