### ISSUE TITLE
Upgrading makes apps missing

### ISSUE THREAD

**Issue by qiujiyan** [iVoider/PlayCover#90]
After directly dragging and upgrading the application, the previously installed application is no longer in the list. How should it be re-imported? Or how to completely uninstall the previous app?Thanks！

I can find the previous application in the directory "/Users/myUserName/Library/Containers/me.playcover.PlayCover". Does dragging the ipa file again make the app reimport? Are the data packages downloaded inside the app here? For example, Genshin Impact needs to download several files after the installation is complete. How to re-import or delete these files?Thanks！

**Comment by sheaahhoi1** [comment]
PlayCover Right click Genshin APP ICO

**Comment by iVoider** [comment]
When you install new version, no need manipulate with files. For deleting you will need to wait latest supporter release come for everyone.
