### ISSUE TITLE
Controls stop working in Genshin Impact

### ISSUE THREAD

**Issue by ciconini** [iVoider/PlayCover#97]
I'm facing some issues with Genshin Impact app, the controls suddenly stop working, even the alt button stops. Sometimes only the LMB works.
I'm using the PlayCover v0.9.7 on macOs v12.1

**Comment by TedaLIEz** [comment]
Hi @ciconini, I didn't make it work with my ps4 controller either. I've paired my controller through bluetooth successfully but it can't controll in Genshin Impact. Should I set up the key mapping manually to make it work?

**Comment by iVoider** [comment]
Try 0.9.8 release and make mouse / trackpad sensivity smaller. About controller: you need to turn it on in Genshin settings after tutorial
